name       : printrun
version    : 1.6.0
release    : 1
source     :
    - https://github.com/kliment/Printrun/archive/printrun-1.6.0.tar.gz : fefcb4c5793fc77205a14263bc915616cde0523cd60704f356191b9ae34ba65d
license    : GPL-3.0
component  : office
summary    : Pronterface, Pronsole, and Printcore - Pure Python 3d printing host software 
description: |
    Printrun consists of printcore, pronsole and pronterface, and a small collection of helpful scripts.
    
    * printcore.py is a library that makes writing reprap hosts easy
    * pronsole.py is an interactive command-line host software with tabcompletion goodness
    * pronterface.py is a graphical host software with the same functionality as pronsole
builddeps  :
    - cython
    - python-pyserial
    - python-setuptools
rundeps    :
    - numpy     # enable 3D view (optional)
    - python-psutil
    - python-pyglet
    - python-pyserial
    - wxPython
build      : |
    # Let the macro do its job, but we want different build options.
    # https://github.com/kliment/Printrun#cython-based-g-code-parser
    %python_setup
    pushd $PKG_BUILD_DIR/py2build
        python setup.py build_ext --inplace
    popd
install    : |
    %python_install
